on:
  push:
    branches: [ Releases ]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - id: publish
        name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with: 
          token: ${{ secrets.NPM_TOKEN }}
          registry: http://184.168.126.153:4873/
          package: ${{ github.workspace }}/Assets/MCU_ProjectID/package.json
      - if: steps.publish.outputs.type != 'none'
        name: GitHub Version
        uses: quabug/create-upm-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upm_package_path: ${{ github.workspace }}/Assets/MCU_ProjectID/
          upm_tag_prefix: v